### PR TITLE
Fixed Control law error in LQRController

### PR DESCRIPTION
**Pull request by Haricharan1212**
### Bugs:
- The control law used was $u = -K y$, while instead it should've been $u = - K \Delta y$.

### Changes Made:
- `__init__`  takes `moment_of_inertia` as a parameter for added functionality
- The function `set_goal` previously had no functionality, now it sets the goal of the controller and recomputes $A$, $K$, and $S$ matrices
- The control law is changed to $u = -K (y - y_\text{goal})$

### Testing:
- I tested these changes in our TMotors setup, and they are functional

### CODE REVIEW

**Comment by shivesh1210** [comment]
Thanks for the PR. Delta y is not needed because we perform a change of coordinates around that configuration. If you choose to do so, you have to also correct your L133 where the expression on LHS should be Delta y * S * Delta y.

**Comment by Haricharan1212** [comment]
It is updated now

**Comment by Haricharan1212** [comment]
Sir,

I have updated the function now. The class is now more modular and has more
features. Please look into merging the changes.

Regards,
Haricharan B,
Second Year Undergraduate,
Indian Institute of Technology, Madras

**Comment by fwiebe** [comment]
Hi @Haricharan1212 
Thanks for your PR.
I have the following comments to your changes:

1. I think there is a mistake in the A matrix. If you introduce inertia and evaluate the matrix at an arbitrary goal, I think the lower left entry should be 

   `-self.mass*self.g*self.len / self.moment_of_inertia*np.cos(self.goal[0])`

   instead of:

   `-self.g * np.cos(self.goal[0])/(2 * self.len)`

2. The angle wrapping is missing. The position error should be wrapped so that there is no discontinuity around the goal position. The angle should be wrapped like

   `delta_pos = pos - self.goal[0]`
   `delta_pos_wrapped = (delta_pos + np.pi) % (2*np.pi) - np.pi`

3. I would propose to rename the variable `moment_of_inertia` to simply `inertia`. This is then consistent with the other controllers and the pendulum plant.

If you can address these comments, I will gladly merge your PR.

Best Regards

**Comment by Haricharan1212** [comment]
Hi,

I think I've addressed the above comments.

Best Regards

**Review by fwiebe — APPROVED** [review]
my comments from the conversation have been addressed

**Pull request merged**
